Algoritmo "condicional"
// 
//  
// Descrição   : estrutura condicionada! (função)
// Autor(a)    : Darling
// Data atual  : 14/08/2021
Var
    numero : inteiro


Inicio
      Escreva ("Digite um numero qualquer: ")
      Leia (numero)
      Se (numero % 2 = 0) entao
            Escreva ("O numero digitado",numero," e PAR")
      Senao (numero % 2 = 1) entao
            Escreva ("O numero digitado", numero," e IMPAR")
      FimSe



Fimalgoritmo