Algoritmo "Enquantofinal"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Darling
// Data atual  : 17/08/2021
Var
     contador, valor :inteiro


Inicio
      contador <- 0
      Escreva ("Ate qual o valor voce deseja contar? ")
      Leia (valor)
      Enquanto (contador <= valor) faca
               Escreval (contador)
               contador <- contador + 1

      FimEnquanto


Fimalgoritmo