Algoritmo "Enquantopergunta"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Darling
// Data atual  : 16/08/2021
Var
   contador, numero:inteiro


Inicio
      Escreva ("Ate qual numero voce precisa contar? ")
      Leia (numero)
      contador <- 0
      Enquanto (contador <= numero) faca
         Escreval (contador)
         contador <- contador + 1
      FimEnquanto
      Escreva ("Terminei de contar")


Fimalgoritmo