Algoritmo "media"

Var
   nota1, nota2, media: real
   nome:caractere


Inicio
      Escreva ("Qual o seu nome? ")
      Leia (nome)
      Escreva(nome, " digite a sua primeira nota: ")
      leia (nota1)
      Escreva (nome, " digite a sua segunda nota: ")
      leia (nota2)
      media <- (nota1 + nota2)/2
      Escreva (nome, " a media entre",nota1," e",nota2, " e igual a", media)


Fimalgoritmo