Algoritmo "Procedimentosoma"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Darling
// Data atual  : 29/08/2021
Var
   x,y:inteiro

   Procedimento Soma (A,B:inteiro)
   
   inicio
         Escreval ("Escreva o valor",A)
         Escreval ("Escreva o valor",B)
         Escreval ("A soma de entre os dois é:",A+B)

   FimProcedimento
   


Inicio

      x<- 5
      y<- 3
      Soma (x,y)


Fimalgoritmo