Algoritmo "repeticaoPara"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Darling
// Data atual  : 27/08/2021
Var
    contador: inteiro


Inicio

      Para contador<-1 ate 10 faca
           Escreva (contador,"..")
      FimPara

      Para contador<-1 ate 20 passo 2 faca
           Escreva (contador,"..")
      FimPara
      
      Para contador<-1 ate 30 passo 3 faca
           Escreva (contador,"..")
      FimPara
      
      
Fimalgoritmo